FROM python:3.9-alpine

WORKDIR /app

COPY requirements.txt /app
RUN python -m pip install -r requirements.txt

COPY index.html /app
COPY main-fastapi.py /app

EXPOSE 22614

CMD python -m uvicorn --host 0.0.0.0 --port 22614 main-fastapi:app
