FROM python:3.9-alpine

WORKDIR /app

COPY requirements.txt /app
RUN python -m pip install -r requirements.txt

COPY index.html /app
COPY main-aiohttp.py /app

EXPOSE 22614

CMD python main-aiohttp.py